//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Ru.GameSchool.DataLayer.Repository
{
    public partial class LevelExamAnswer
    {
        #region Primitive Properties
    
        public virtual int LevelExamAnswerId
        {
            get;
            set;
        }
    
        public virtual int LevelExamQuestionId
        {
            get { return _levelExamQuestionId; }
            set
            {
                if (_levelExamQuestionId != value)
                {
                    if (LevelExamQuestion != null && LevelExamQuestion.LevelExamQuestionId != value)
                    {
                        LevelExamQuestion = null;
                    }
                    _levelExamQuestionId = value;
                }
            }
        }
        private int _levelExamQuestionId;
    
        public virtual string Answer
        {
            get;
            set;
        }
    
        public virtual bool Correct
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual LevelExamQuestion LevelExamQuestion
        {
            get { return _levelExamQuestion; }
            set
            {
                if (!ReferenceEquals(_levelExamQuestion, value))
                {
                    var previousValue = _levelExamQuestion;
                    _levelExamQuestion = value;
                    FixupLevelExamQuestion(previousValue);
                }
            }
        }
        private LevelExamQuestion _levelExamQuestion;

        #endregion
        #region Association Fixup
    
        private void FixupLevelExamQuestion(LevelExamQuestion previousValue)
        {
            if (previousValue != null && previousValue.LevelExamAnswers.Contains(this))
            {
                previousValue.LevelExamAnswers.Remove(this);
            }
    
            if (LevelExamQuestion != null)
            {
                if (!LevelExamQuestion.LevelExamAnswers.Contains(this))
                {
                    LevelExamQuestion.LevelExamAnswers.Add(this);
                }
                if (LevelExamQuestionId != LevelExamQuestion.LevelExamQuestionId)
                {
                    LevelExamQuestionId = LevelExamQuestion.LevelExamQuestionId;
                }
            }
        }

        #endregion
    }
}
