//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Ru.GameSchool.DataLayer.Repository
{
    public partial class LevelExamUserAnswer
    {
        #region Primitive Properties
    
        public virtual int LevelExamUserAnswerId
        {
            get;
            set;
        }
    
        public virtual int LevelExamAnswerId
        {
            get { return _levelExamAnswerId; }
            set
            {
                if (_levelExamAnswerId != value)
                {
                    if (LevelExamAnswer != null && LevelExamAnswer.LevelExamAnswerId != value)
                    {
                        LevelExamAnswer = null;
                    }
                    _levelExamAnswerId = value;
                }
            }
        }
        private int _levelExamAnswerId;
    
        public virtual int UserInfoId
        {
            get { return _userInfoId; }
            set
            {
                if (_userInfoId != value)
                {
                    if (UserInfo != null && UserInfo.UserInfoId != value)
                    {
                        UserInfo = null;
                    }
                    _userInfoId = value;
                }
            }
        }
        private int _userInfoId;

        #endregion
        #region Navigation Properties
    
        public virtual LevelExamAnswer LevelExamAnswer
        {
            get { return _levelExamAnswer; }
            set
            {
                if (!ReferenceEquals(_levelExamAnswer, value))
                {
                    var previousValue = _levelExamAnswer;
                    _levelExamAnswer = value;
                    FixupLevelExamAnswer(previousValue);
                }
            }
        }
        private LevelExamAnswer _levelExamAnswer;
    
        public virtual UserInfo UserInfo
        {
            get { return _userInfo; }
            set
            {
                if (!ReferenceEquals(_userInfo, value))
                {
                    var previousValue = _userInfo;
                    _userInfo = value;
                    FixupUserInfo(previousValue);
                }
            }
        }
        private UserInfo _userInfo;

        #endregion
        #region Association Fixup
    
        private void FixupLevelExamAnswer(LevelExamAnswer previousValue)
        {
            if (previousValue != null && previousValue.LevelExamUserAnswers.Contains(this))
            {
                previousValue.LevelExamUserAnswers.Remove(this);
            }
    
            if (LevelExamAnswer != null)
            {
                if (!LevelExamAnswer.LevelExamUserAnswers.Contains(this))
                {
                    LevelExamAnswer.LevelExamUserAnswers.Add(this);
                }
                if (LevelExamAnswerId != LevelExamAnswer.LevelExamAnswerId)
                {
                    LevelExamAnswerId = LevelExamAnswer.LevelExamAnswerId;
                }
            }
        }
    
        private void FixupUserInfo(UserInfo previousValue)
        {
            if (previousValue != null && previousValue.LevelExamUserAnswers.Contains(this))
            {
                previousValue.LevelExamUserAnswers.Remove(this);
            }
    
            if (UserInfo != null)
            {
                if (!UserInfo.LevelExamUserAnswers.Contains(this))
                {
                    UserInfo.LevelExamUserAnswers.Add(this);
                }
                if (UserInfoId != UserInfo.UserInfoId)
                {
                    UserInfoId = UserInfo.UserInfoId;
                }
            }
        }

        #endregion
    }
}
