//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Ru.GameSchool.DataLayer.Repository
{
    public partial class LevelProjectResult
    {
        #region Primitive Properties
    
        public virtual int LevelProjectResultId
        {
            get;
            set;
        }
    
        public virtual int UserInfoId
        {
            get { return _userInfoId; }
            set
            {
                if (_userInfoId != value)
                {
                    if (UserInfo != null && UserInfo.UserInfoId != value)
                    {
                        UserInfo = null;
                    }
                    _userInfoId = value;
                }
            }
        }
        private int _userInfoId;
    
        public virtual string TeacherFeedback
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateDateTime
        {
            get;
            set;
        }
    
        public virtual string UserFeedback
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GradeDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> ContentID
        {
            get;
            set;
        }
    
        public virtual int LevelProjectId
        {
            get { return _levelProjectId; }
            set
            {
                if (_levelProjectId != value)
                {
                    if (LevelProject != null && LevelProject.LevelProjectId != value)
                    {
                        LevelProject = null;
                    }
                    _levelProjectId = value;
                }
            }
        }
        private int _levelProjectId;
    
        public virtual Nullable<double> Grade
        {
            get;
            set;
        }
    
        public virtual string Filename
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual LevelProject LevelProject
        {
            get { return _levelProject; }
            set
            {
                if (!ReferenceEquals(_levelProject, value))
                {
                    var previousValue = _levelProject;
                    _levelProject = value;
                    FixupLevelProject(previousValue);
                }
            }
        }
        private LevelProject _levelProject;
    
        public virtual UserInfo UserInfo
        {
            get { return _userInfo; }
            set
            {
                if (!ReferenceEquals(_userInfo, value))
                {
                    var previousValue = _userInfo;
                    _userInfo = value;
                    FixupUserInfo(previousValue);
                }
            }
        }
        private UserInfo _userInfo;

        #endregion
        #region Association Fixup
    
        private void FixupLevelProject(LevelProject previousValue)
        {
            if (previousValue != null && previousValue.LevelProjectResults.Contains(this))
            {
                previousValue.LevelProjectResults.Remove(this);
            }
    
            if (LevelProject != null)
            {
                if (!LevelProject.LevelProjectResults.Contains(this))
                {
                    LevelProject.LevelProjectResults.Add(this);
                }
                if (LevelProjectId != LevelProject.LevelProjectId)
                {
                    LevelProjectId = LevelProject.LevelProjectId;
                }
            }
        }
    
        private void FixupUserInfo(UserInfo previousValue)
        {
            if (previousValue != null && previousValue.LevelProjectResults.Contains(this))
            {
                previousValue.LevelProjectResults.Remove(this);
            }
    
            if (UserInfo != null)
            {
                if (!UserInfo.LevelProjectResults.Contains(this))
                {
                    UserInfo.LevelProjectResults.Add(this);
                }
                if (UserInfoId != UserInfo.UserInfoId)
                {
                    UserInfoId = UserInfo.UserInfoId;
                }
            }
        }

        #endregion
    }
}
