//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Ru.GameSchool.DataLayer.Repository
{
    public partial class Status
    {
        #region Primitive Properties
    
        public virtual int StatusId
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<UserInfo> UserInfoes
        {
            get
            {
                if (_userInfoes == null)
                {
                    var newCollection = new FixupCollection<UserInfo>();
                    newCollection.CollectionChanged += FixupUserInfoes;
                    _userInfoes = newCollection;
                }
                return _userInfoes;
            }
            set
            {
                if (!ReferenceEquals(_userInfoes, value))
                {
                    var previousValue = _userInfoes as FixupCollection<UserInfo>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUserInfoes;
                    }
                    _userInfoes = value;
                    var newValue = value as FixupCollection<UserInfo>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUserInfoes;
                    }
                }
            }
        }
        private ICollection<UserInfo> _userInfoes;

        #endregion
        #region Association Fixup
    
        private void FixupUserInfoes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UserInfo item in e.NewItems)
                {
                    item.Status = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UserInfo item in e.OldItems)
                {
                    if (ReferenceEquals(item.Status, this))
                    {
                        item.Status = null;
                    }
                }
            }
        }

        #endregion
    }
}
