//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Ru.GameSchool.DataLayer.Repository
{
    public partial class sysdiagram
    {
        #region Primitive Properties
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual int principal_id
        {
            get;
            set;
        }
    
        public virtual int diagram_id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> version
        {
            get;
            set;
        }
    
        public virtual byte[] definition
        {
            get;
            set;
        }

        #endregion
    }
}
