//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Ru.GameSchool.DataLayer.Repository
{
    public partial class UserLog
    {
        #region Primitive Properties
    
        public virtual int UserLogId
        {
            get;
            set;
        }
    
        public virtual System.DateTime LoginTime
        {
            get;
            set;
        }
    
        public virtual string IpAddress
        {
            get;
            set;
        }
    
        public virtual int UserInfoId
        {
            get { return _userInfoId; }
            set
            {
                if (_userInfoId != value)
                {
                    if (UserInfo != null && UserInfo.UserInfoId != value)
                    {
                        UserInfo = null;
                    }
                    _userInfoId = value;
                }
            }
        }
        private int _userInfoId;

        #endregion
        #region Navigation Properties
    
        public virtual UserInfo UserInfo
        {
            get { return _userInfo; }
            set
            {
                if (!ReferenceEquals(_userInfo, value))
                {
                    var previousValue = _userInfo;
                    _userInfo = value;
                    FixupUserInfo(previousValue);
                }
            }
        }
        private UserInfo _userInfo;

        #endregion
        #region Association Fixup
    
        private void FixupUserInfo(UserInfo previousValue)
        {
            if (previousValue != null && previousValue.UserLogs.Contains(this))
            {
                previousValue.UserLogs.Remove(this);
            }
    
            if (UserInfo != null)
            {
                if (!UserInfo.UserLogs.Contains(this))
                {
                    UserInfo.UserLogs.Add(this);
                }
                if (UserInfoId != UserInfo.UserInfoId)
                {
                    UserInfoId = UserInfo.UserInfoId;
                }
            }
        }

        #endregion
    }
}
